ReeldIn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls", namespace="landing_page")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "recommendations/", include("recommendations.urls", namespace="recommendations")
    ),
    path("__reload__/", include("django_browser_reload.urls")),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

djangotemplate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("__reload__/", include("django_browser_reload.urls")),
]

landing_page/urls.py
from django.urls import path, include
from . import views

app_name = "landing_page"

urlpatterns = [
    path("", views.index, name="index"),
    path("get-csrf-token/", views.get_csrf_token, name="get_csrf_token"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("search/movies", views.search_movies, name="search_movies"),
    path("movie/", views.movie, name="movie"),
    path("api/search/movies", views.search_movies_json, name="search_movies_json"),
]

landing_page/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from recommendations.models import Movie
from django.db.models import Q, CharField, TextField
from django.middleware.csrf import get_token
import json


# Initial landing page view.
def index(request):
    return render(request, "landing_page/index.html")


def about(request):
    return render(request, "landing_page/about.html")


def contact(request):
    return render(request, "landing_page/contact.html")

def about(request):
    return render(request, "landing_page/about.html")

#testing purposes
def movie(request):
    return render(request, "landing_page/movie.html")

def get_csrf_token(request):
    csrf_token = get_token(request)
    return JsonResponse({"csrf_token": csrf_token})


def search_movies(request):
    query = request.GET.get("query")

    if query:
        # Get all field names of the Movie model
        movie_fields = [
            field.name
            for field in Movie._meta.get_fields()
            if isinstance(field, (CharField, TextField))
        ]

        # Construct a list of Q objects for each field
        q_objects = [Q(**{f"{field}__icontains": query}) for field in movie_fields]

        # Combine all Q objects using OR operator
        # movies = Movie.objects.filter(*q_objects).distinct()
        # json_movies = [{"movie": movie} for movie in movies]
        json_movies = [
            {"name": "spiderman", "year": 2023},
            {"name": "batman", "year": 1999},
        ]

        return render(request, "landing_page/movie.html", {"movies": json_movies})

    return redirect("")


def search_movies_json(request):
    if request.method == "POST":
        # Decode the request body
        body_unicode = request.body.decode("utf-8")

        # Parse the JSON data
        body_data = json.loads(body_unicode)

        # Access specific fields from the JSON data
        search_string = body_data.get("search")
        movies = [{"name": "Batman Begins"}]

        if search_string and False:  # And False until the DB works
            movies = Movie.objects.filter(name__icontains=search_string)

        # Perform search operation and get the result
        result = {"movies": movies}  # Your search result data here

        # Return the result as JSON response
        return JsonResponse(result, status=200)

    # Return an error response for non-POST requests
    return JsonResponse({"error": "Method not allowed"}, status=405)

landing_page/templates/landing_page/about.html
{% extends 'landing_page/base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'landing_page/css/about.css' %}" />

<div id="message_div">
  <h1>Learn More about ReeldIn</h1>
</div>
<div class="content_div">
  <div id="title_div">
    <h2>What is ReeldIn?</h2>
  </div>

  <div class="about_div">
    <p>
      Movies are a highly valued creative outlet and pastime, but frequently,
      it's hard to choose one. With millions available and more releasing daily,
      the hurdle of picking something to watch can be daunting. ReeldIn intends
      to match users with movies they'll enjoy. Our product is sleek, quick. and
      efficient. We use a combination of user input and machine learning to
      provide the best recommendations possible. We're here to make your
      movie-watching experience as enjoyable as possible.
    </p>

    <br />
    <h2>FAQ</h2>
    <br />
    <h3>Q: How do I make an account?<br /></h3>
    <br />
    <p>
      A: To make an account, click the "Login" button in the top right corner of
      the page. You'll be prompted to input your email and password. Once you've
      done that, you'll have access to all of ReeldIn's features.
    </p>
    <br />
    <h3>Q: How do I get recommendations? <br /></h3>
    <br />
    <p>A: To get recommendations...</p>
    <br />
    <h3>Q: How does ReeldIn work? <br /></h3>
    <br />
    <p>
      A: ReeldIn uses a combination of user input and machine learning to
      provide the best recommendations possible. Users can input their favorite
      movies, and ReeldIn will use that information to suggest similar movies.
    </p>
  </div>
</div>

{% endblock content %}

landing_page/templates/landing_page/base.html
{% load static %} {% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% csrf_token %}
    <script
      src="https://kit.fontawesome.com/c60455fa26.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'landing_page/js/index.js' %}" defer></script>
    <link
      rel="stylesheet"
      href="{% static 'landing_page/css/base.css' %}"
    />
    <link rel="stylesheet" href="{% static 'landing_page/css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'landing_page/css/about.css' %}" />
    <title>ReeldIn</title>
    
  </head>

  <header>

    <div id="logo_div">
      <a href="{% url 'landing_page:index' %}">
        <img src="{% static 'landing_page/images/REELDIN.png' %}" alt="ReeldIn Logo" />
      </a>
      <a href="{% url 'landing_page:index' %}">
        <h1>ReeldIn</h1>
      </a>
    </div>
    <div id="searchbar_div">
      <input
        type="text"
        id="searchbar"
        name="searchbar"
        placeholder="Search for movies..."
        onkeyup="searchMovies(event)"
      />
      <i class="fa-solid fa-magnifying-glass"></i>
      <div id="searched_movies_container"></div>
    </div>
    <div id="profile_div">
      <a href="{% url 'recommendations:index' %}">
        <button id="get_recommendations_btm">
          Get Recommendations
        </button>
      </a>
      <a href="{% url 'accounts:login' %}">
        <button id="login_button">Login</button>
      </a>
      <img id="profile_pic" src="{% static 'landing_page/images/profile.png' %}" />
      </img>
  </header>

  <nav>
    <a href="{% url 'landing_page:index' %}"> Home</a>
    <a href="{% url 'landing_page:about' %}">About</a>
    <!-- remove movie tab from nav later, testing only-->
    <a href="{% url 'landing_page:movie' %}">movie</a>
  </nav>

  <body>
    <input type="hidden" id="csrf_token" value="{% csrf_token %}">
    {% block content %} {% endblock content %}
  </body>

  <footer>
    <div id="footer_nav">
      <a href="{% url 'landing_page:index' %}">Home</a>
      <a href="profile.html">Profile</a>
      <a href="search.html">Search</a>
      <a href="20Qs.html">20 Questions</a>
      <a href="{% url 'landing_page:about' %}">About</a>
      <a href="{% url 'landing_page:contact' %}">Contact Us</a>
      <a href="team.html">Our Team</a>
    </div>
    <div id="copyright">
      <p>ReeldIn 2024 &copy;</p>
    </div>
  </footer>

</html>

landing_page/templates/landing_page/contact.html
{% extends 'landing_page/base.html' %} {% load static %} {% block content %}

<!-- 
The following files have been adapted from "html-form-examples-templates" by FormBold
- accounts/templates/accounts/contact.html
- accounts/static/accounts/css/contact.css

Github Repo: https://github.com/FormBold/html-form-examples-templates
Learn More: https://formbold.com
-->

<link rel="stylesheet" href="{% static 'landing_page/css/contact.css' %}" />

<div id="message_div">
  <h1 id="title">Contact Us</h1>
</div>
<div class="content_div">
  <div class="content_container">
    <div class="formbold-form-wrapper">
      <!-- https://formsubmit.co/> -->
      <form action="https://formsubmit.co/temp@email.com" method="POST">
        <div class="formbold-mb-5">
          <label for="name" class="formbold-form-label"> Full Name </label>
          <input
            type="text"
            name="name"
            id="name"
            placeholder="Full Name"
            class="formbold-form-input"
          />
        </div>

        <div class="formbold-mb-5">
          <label for="email" class="formbold-form-label"> Email Address </label>
          <input
            type="email"
            name="email"
            id="email"
            placeholder="Enter your email"
            class="formbold-form-input"
          />
        </div>

        <div class="formbold-mb-5">
          <label for="subject" class="formbold-form-label"> Subject </label>
          <input
            type="text"
            name="subject"
            id="subject"
            placeholder="Enter your subject"
            class="formbold-form-input"
          />
        </div>

        <div class="formbold-mb-5">
          <label for="message" class="formbold-form-label"> Message </label>
          <textarea
            rows="6"
            name="message"
            id="message"
            placeholder="Type your message"
            class="formbold-form-input"
          ></textarea>
        </div>

        <div>
          <button class="formbold-btn">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

landing_page/templates/landing_page/index.html
{% extends 'landing_page/base.html' %} {% load static %} {% block content %}

<div id="message_div">
  <h1>Welcome to ReeldIn</h1>
</div>
<div class="content_div">
  <div id="title_div">
    <h2>Latest Recommendations...</h2>
  </div>
  <div class=" movies_div content_container">
    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>

    <div class="movie tooltip">
      <div class="tooltiptext">
        <h3>Spiderman: Into the Spiderverse</h3>
        <p>Rating: 4.5/5</p>
        <p>Genre: Animation, Action, Adventure</p>
        <p>Year: 2018</p>
        <p>Director: Bob Persichetti, Peter Ramsey, Rodney Rothman</p>
        <button>Click</button>
      </div>

      <img src="{% static 'landing_page/images/spiderverse.webp' %}" alt="Movie 1" />
    </div>
  </div>
</div>

{% endblock content %}

landing_page/templates/landing_page/movie.html
{% extends 'landing_page/base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'landing_page/css/movie.css' %}" />
<script src="{% static 'landing_page/js/movie.js' %}"></script>
<div id="message_div">
    <h1>Movie Info Page</h1>
</div>
<div id="content_div"></div>
<div id="movie_name">
    <h2>Dark Knight</h2>
    <div id="movie_button_nav">
        <!-- For testing purposes -->
        <button id="movie-button" onclick="movieOverview()">Overview</button>
        <button id="movie-button" onclick="movieDetails()">Details </button>
        <button id="movie-button" onclick="movieWatching()">Watching</button>
        <button id="movie-button" onclick="movieOptions()">Opinions</button>
    </div>

</div>
<div class="content_container">
    <img 
        src="{% static 'landing_page/images/darkknight.webp' %}"
        alt="The Batman Movie Poster" 
        />
        <p id="movie_summary"> 

        </p>
    </div>
</div>    
{% endblock content %}