ReeldIn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls", namespace="landing_page")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "recommendations/", include("recommendations.urls", namespace="recommendations")
    ),
    path("__reload__/", include("django_browser_reload.urls")),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

djangotemplate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("__reload__/", include("django_browser_reload.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from recommendations.models import Movie


# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=30)
    email = models.EmailField(max_length=254)
    friends = models.ManyToManyField("User", blank=True)

    # external accounts, used for connections
    letterboxd_username = models.CharField(
        max_length=15, unique=True, null=True, blank=True
    )
    imdb_user_id = models.CharField(max_length=32, unique=True, null=True, blank=True)

    # 'Movie' connections - movies already seen and movies already recommended
    seen_films = models.ManyToManyField(Movie, related_name="users_seen", blank=True)
    recommended_films = models.ManyToManyField(
        Movie, related_name="users_recommended", blank=True
    )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from .forms import CustomUserCreationForm
from .models import User


def login_view(request):

    # prevents access by logged in users
    if request.user.is_authenticated:
        return redirect("dashboard:index")

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("dashboard:index")
        else:
            return render(
                request,
                "accounts/login.html",
                {"message": "Invalid username and/or password"},
            )
    elif request.method == "GET":
        return render(request, "accounts/login.html")


def logout_view(request):
    logout(request)
    return redirect("accounts:login")


def register_view(request):

    # prevents access by logged in users
    if request.user.is_authenticated:
        return redirect("dashboard:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("dashboard:index")
        else:
            # checks if username is taken
            username = request.POST["username"]
            if User.objects.filter(username=username).exists():
                return render(
                    request,
                    "accounts/register.html",
                    {"form": form, "message": "Username has already been taken"},
                )
            # checks if email is taken
            email = request.POST["email"]
            if User.objects.filter(email=email).exists():
                return render(
                    request,
                    "accounts/register.html",
                    {"form": form, "message": "Email address is already in use"},
                )
            password1 = request.POST["password1"]
            confirm = request.POST["password2"]
            if password1 != confirm:
                return render(
                    request,
                    "accounts/register.html",
                    {"form": form, "message": "Passwords do not match"},
                )

            return render(
                request,
                "accounts/register.html",
                {"form": form, "message": "An unknown error occured."},
            )
    elif request.method == "GET":
        form = CustomUserCreationForm()
        return render(request, "accounts/register.html", {"form": form})

accounts/templates/accounts/base.html
<!-- 
The following files have been adapted from "Animated-LoginForm" by Rahman Samadzade
- accounts/templates/accounts/index.html
- accounts/static/accounts/css/login.css
- accounts/static/accounts/js/login.js

Github Repo: https://github.com/capwan/Animated-LoginForm
-->

{% load static %} {% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <link>
    {% tailwind_css %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{% static 'landing_page/images/favicon.png' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}" />
    <title>ReeldIn {% block title%} {% endblock %}</title>
  </link>
  <body>
    {% block form %} {% endblock form %}
  </body>
  <script src="{% static 'accounts/js/login.js' %}"></script>

</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %} {% load static %} {% block form %}

<div class="container" id="container">
  <div class="form-container sign-up">
    <form action="{% url 'accounts:register' %}" method="post">
      {% csrf_token %}
      <h1>Create Account</h1>
      <input type="text" placeholder="Name" />
      <input type="email" placeholder="Email" />
      <input type="password" placeholder="Password" />
      <button>Sign Up</button>
    </form>
  </div>

  <div class="form-container sign-in">
    <form action="{% url 'accounts:login' %}" method="post">
      {% csrf_token %}
      <h1>Sign In</h1>
      <input type="email" placeholder="Email" />
      <input type="password" placeholder="Password" />
      <a href="">Forgot your email or password?</a>
      <button>Sign in</button>
    </form>
  </div>

  <div class="toggle-container">
    <div class="toggle">
      <div class="toggle-panel toggle-left">
        <h1>Welcome Back!</h1>
        <p>Enter your personal details to use all of site features</p>
        <button class="hidden" id="login">Sign In</button>
      </div>
      <div class="toggle-panel toggle-right">
        <h1>Hello, User!</h1>
        <p>Register with your personal details to use all of site features</p>
        <button class="hidden" id="register">Sign Up</button>
      </div>
    </div>
  </div>
</div>

{% endblock form %}

accounts/templates/accounts/login_example.html
{% extends 'accounts/base.html' %} {% load static %}

{% block title %}Login{%endblock title %} 

{% block form %}
<form action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}

  <h1>Log In</h1>

  {% if message %}
  <p class="error">{{ message }}</p>
  {% endif %}
  <input class="form-group">
    <p class="field-label">Username</p>
    <input type="text" name="username" id="username" />
  </input>

  <div class="form-group">
    <p class="field-label">Password</p>
    <input type="password" name="password" id="password" />
  </div>

  <input type="submit" value="Log In" />

  <p class="dont-have">
    Don't have an account?
    <a href="{% url 'accounts:register' %}">Register here.</a>
  </p>
</form>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}Register{% endblock title %}

{% block form %}
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}

        <h1>Register</h1>

        {% if message %}
            <p class="error">{{ message }}</p>
        {% endif %}
        
        {% for field in form %}
            <div class="form-group">
                <p class="field-label">
                    {{ field.label }}
                </p>
                {{ field }}
            </div>
        {% endfor %}

        <input type="submit" value="Sign Up">

        <p class="dont-have">
            Already have an account? <a href="{% url 'accounts:login' %}">Login here.</a>
        </p>

    </form>

   
{% endblock %}