ReeldIn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls", namespace="landing_page")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "recommendations/", include("recommendations.urls", namespace="recommendations")
    ),
    path("__reload__/", include("django_browser_reload.urls")),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

djangotemplate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("__reload__/", include("django_browser_reload.urls")),
]

landing_page/urls.py
from django.urls import path, include
from . import views

app_name = "landing_page"

urlpatterns = [
    path("", views.index, name="index"),
    path("get-csrf-token/", views.get_csrf_token, name="get_csrf_token"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("search/movies", views.search_movies, name="search_movies"),
    path("movie/", views.movie, name="movie"),
    path("api/search/movies", views.search_movies_json, name="search_movies_json"),
]

recommendations/urls.py
from django.urls import path
from . import views

app_name = "recommendations"

urlpatterns = [
    path("", views.index, name="index"),
    path("recommend/", views.recommend_view, name="recommend"),
]

recommendations/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from .choices import *


class Movie(models.Model):
    name = models.CharField(max_length=105)
    genres = ArrayField(models.CharField(max_length=13, choices=GENRES))
    year = models.PositiveIntegerField()
    runtime = models.PositiveIntegerField()
    language = models.CharField(max_length=2, choices=LANGUAGES)
    budget = models.BigIntegerField(default=0)
    revenue = models.BigIntegerField(default=0)

    poster = models.TextField()
    overview = models.TextField()
    tagline = models.TextField()

    # people
    starring = ArrayField(models.CharField(max_length=60))
    director = ArrayField(models.CharField(max_length=60))
    writer = ArrayField(models.CharField(max_length=60))
    cinematographer = ArrayField(models.CharField(max_length=60))
    composer = ArrayField(models.CharField(max_length=60))

    watch_providers = ArrayField(models.CharField(max_length=60, choices=STREAMING))
    keywords = ArrayField(models.CharField(max_length=60))
    tmdb_id = models.PositiveIntegerField()
    imdb_rating = models.DecimalField(max_digits=10, decimal_places=2)
    imdb_votes = models.PositiveIntegerField()


class Recommendation(models.Model):
    possible_films = models.ManyToManyField("Movie", related_name="recommendations")
    possible_film_count = models.PositiveIntegerField()

    # answers
    genres = ArrayField(models.CharField(max_length=13, choices=GENRES))
    year_span = models.PositiveIntegerField(choices=YEAR_SPANS)
    runtime_span = models.PositiveIntegerField(choices=RUNTIME_SPANS)
    languages = ArrayField(models.CharField(max_length=2, choices=LANGUAGES))
    triggers = ArrayField(models.CharField(max_length=100, choices=TRIGGERS))
    watch_providers = ArrayField(models.CharField(max_length=60, choices=STREAMING))

    preferred_cast = ArrayField(models.CharField(max_length=60))
    preferred_crew = ArrayField(models.CharField(max_length=60))
    excluded_cast = ArrayField(models.CharField(max_length=60))
    excluded_crew = ArrayField(models.CharField(max_length=60))

    popular = models.BooleanField(default=False)
    well_reviewed = models.BooleanField(default=True)
    external_account_influence = models.BooleanField(default=False)

    # TODO jokey questions

recommendations/forms.py
from django import forms
from .choices import *


class GenreForm(forms.Form):
    Question = forms.CharField(
        initial="Let's pick your desired genre(s)!", disabled=True, max_length=50
    )

    OPTIONS = GENRES
    Genres = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=OPTIONS,
        help_text=(
            "Note: Your selected movie will have an element of all these genres "
            "so if you select 'romance' and 'comedy', we'll find rom-coms for you."
        ),
    )


class YearForm(forms.Form):
    Question = forms.CharField(
        initial="What release time frame are you feeling today?",
        disabled=True,
        max_length=50,
    )

    OPTIONS = YEAR_SPANS
    Years = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=OPTIONS
    )

recommendations/views.py
from django.shortcuts import render
from .forms import *
from .models import Recommendation

# TODO make this short and concise and move step-by-step (this is JUST for step 1 -> step 2 right now)
def recommend_view(request):
    form = GenreForm(request.POST)
    if form.is_valid():
        selected_genres = form.cleaned_data.get("Genres", [])
        # Recommendation(genres=selected_genres)
        # Recommendation.save()

    form = YearForm()
    return render(
        request,
        "recommendations/index.html",
        {"form": form},
    )


def index(request):
    form = GenreForm()
    return render(
        request,
        "recommendations/index.html",
        {"form": form},
    )

recommendations/templates/recommendations/base.html
<!-- Practically the same as 'landing_page/base.html' -->

{% load static %} {% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://kit.fontawesome.com/c60455fa26.js" crossorigin="anonymous">
        </script>
        <script src="{% static 'recommendations/js/index.js' %}" defer></script>
        <link rel="stylesheet" href="{% static 'landing_page/css/base.css' %}" />
        <link rel="stylesheet" href="{% static 'recommendations/css/index.css' %}" />
        <title>ReeldIn</title>
    </head>

    <header>

        <div id="logo_div">
            <a href="{% url 'landing_page:index' %}">
                <img src="{% static 'landing_page/images/REELDIN.png' %}"
                    alt="ReeldIn Logo" />
            </a>
            <a href="{% url 'landing_page:index' %}">
                <h1>ReeldIn</h1>
            </a>
        </div>
        <div id="searchbar_div">
            <input type="text" id="searchbar" name="searchbar"
                placeholder="Search for movies..." onkeydown="searchMovies(event)" />
            <i class="fa-solid fa-magnifying-glass"></i>
        </div>
        <div id="profile_div">
            <a href="{% url 'recommendations:index' %}">
                <button id="get_recommendations_btm">
                    Get Recommendations
                </button>
            </a>
            <a href="{% url 'accounts:login' %}">
                <button id="login_button">Login</button>
            </a>
            <img id="profile_pic" src="{% static 'landing_page/images/profile.png' %}" />
            </img>
    </header>

    <nav>
        <a href="{% url 'landing_page:index' %}">Home</a>
        <a href="{% url 'landing_page:about' %}">About</a>
    </nav>

    <body>
        {% block content %} {% endblock content %}
    </body>

    <!-- <footer>
            <div id="footer_nav">
                <a href="{% url 'landing_page:index' %}">Home</a>
                <a href="profile.html">Profile</a>
                <a href="search.html">Search</a>
                <a href="20Qs.html">20 Questions</a>
                <a href="{% url 'landing_page:about' %}">About</a>
                <a href="{% url 'landing_page:contact' %}">Contact Us</a>
                <a href="team.html">Our Team</a>
            </div>
            <div id="copyright">
                <p>ReeldIn 2024 &copy;</p>
            </div>
        </footer> -->

</html>

recommendations/templates/recommendations/index.html
{% extends 'recommendations/base.html' %}
{% load static %}

{% block content %}

<div id="recommendation_space">

    <h1 id="question">Question #1</h1>
    {% block form %}
    <form action="{% url 'recommendations:recommend' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="submit">

    </form>

    <!-- Number will change later -->
    <h1 id="remaining">Remaining Films: 25,063</h1>
</div>

{% endblock %}

{% endblock content %}